### ISSUE TITLE
Addon crashes when login to WHM interface 

### ISSUE THREAD

**Issue by catalinDonici** [SpamExperts/cpanel-addon#21]
### Version information

`Addon version: 3.0.96528`

### Steps to replicate

 1. Add a new account and make it a reseller and own himself
 2. Go to reseller centre 
 3. Login to WHM
 4. Access Professional Spam Filter 

### Actual result

```HTTP error 401

cgi/addon_prospamfilter.cgi

You do not have permission to access this page.
```

### Expected result

See resellers domain list

**Comment by claudiapetre** [comment]
I am not sure if this is a bug, since in https://github.com/SpamExperts/cpanel-addon/blob/master/bin/cpanel/appconfig/prospamfilter_whm.conf I see the addon is restricted to acl="all". 
IMO, since this resseller doesn't have root access, the current behavior is the correct one. 
If we need to allow also others acl levels to our plugin, probably the value from the config file should be changed to "thirdparty".
